test:
  user:
    username: zhangsan
    age: 18
    toString: the age of ${test.user.username} is ${test.user.age}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#mybatis:
#  type-aliases-package: cn.lxk.domain.entity

